---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '6.48'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0402, CPAN::Meta::Converter version 2.150001'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Compare
no_index:
  directory:
    - t
    - inc
requires:
  Clone: '0.43'
  File::Find::Rule: '0.1'
  Scalar::Util: '0'
  Test::More: '0.88'
  perl: '5.006'
resources:
  bugtracker: https://github.com/DrHyde/perl-modules-Data-Compare/issues
  repository: https://github.com/DrHyde/perl-modules-Data-Compare
version: 1.27
